apiVersion: v1
kind: Service
metadata:
  name: {{ include "thesis-diseases-risk-factors-management.fullname" . }}
  labels:
    {{- include "thesis-diseases-risk-factors-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thesis-diseases-risk-factors-management.selectorLabels" . | nindent 4 }}
