apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "thesis-diseases-risk-factors.fullname" . }}
  labels:
    {{- include "thesis-diseases-risk-factors.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  provider: azure
  secretObjects:
    - data:
        - key: entrez-email
          objectName: entrez-email
        - key: db-connection-uri
          objectName: db-connection-uri
        - key: database-name
          objectName: database-name
        - key: redis-host
          objectName: redis-host
        - key: redis-password
          objectName: redis-password
        - key: auth0-domain
          objectName: auth0-domain
        - key: auth0-audience
          objectName: auth0-audience
        - key: auth0-client-secret
          objectName: auth0-client-secret
        - key: storage-account-key
          objectName: storage-account-key
      secretName: {{ include "thesis-diseases-risk-factors.fullname" . }}
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.identityId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    objects: |
      array:
        - |
          objectName: entrez-email
          objectType: secret
        - |
          objectName: db-connection-uri
          objectType: secret
        - |
          objectName: database-name
          objectType: secret
        - |
          objectName: redis-host
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: auth0-domain
          objectType: secret
        - |
          objectName: auth0-audience
          objectType: secret
        - |
          objectName: auth0-client-secret
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
    tenantID: {{ .Values.keyVault.tenantId | quote }}
