# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from .base_model import BaseModel


class Article(BaseModel):
    article: "ArticleArticle"


class ArticleArticle(BaseModel):
    text: str


Article.update_forward_refs()
ArticleArticle.update_forward_refs()
