# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/schema.graphqls

from typing import List

from pydantic import Field

from .base_model import BaseModel


class UpdateRiskFactorsInput(BaseModel):
    disease_id: str = Field(alias="diseaseId")
    risk_factors: List["RiskFactorInput"] = Field(alias="riskFactors")


class RiskFactorInput(BaseModel):
    text: str
    score: float
    articles_ids: List[str] = Field(alias="articlesIds")


UpdateRiskFactorsInput.update_forward_refs()
RiskFactorInput.update_forward_refs()
