# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class ListDiseases(BaseModel):
    diseases: List["ListDiseasesDiseases"]


class ListDiseasesDiseases(BaseModel):
    id: str
    names: List[str]
    db_links: "ListDiseasesDiseasesDbLinks" = Field(alias="dbLinks")
    category: str
    description: str


class ListDiseasesDiseasesDbLinks(BaseModel):
    icd10: Optional[List[str]]
    icd11: Optional[List[str]]
    mesh: Optional[List[str]]


ListDiseases.update_forward_refs()
ListDiseasesDiseases.update_forward_refs()
ListDiseasesDiseasesDbLinks.update_forward_refs()
