# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from typing import List, Optional

from .base_model import BaseModel


class ListQuestionsAnswersByDisease(BaseModel):
    qas: Optional[List["ListQuestionsAnswersByDiseaseQas"]]


class ListQuestionsAnswersByDiseaseQas(BaseModel):
    id: str
    article: "ListQuestionsAnswersByDiseaseQasArticle"
    questions: List["ListQuestionsAnswersByDiseaseQasQuestions"]


class ListQuestionsAnswersByDiseaseQasArticle(BaseModel):
    id: str
    text: str


class ListQuestionsAnswersByDiseaseQasQuestions(BaseModel):
    id: str
    text: str
    answers: List["ListQuestionsAnswersByDiseaseQasQuestionsAnswers"]


class ListQuestionsAnswersByDiseaseQasQuestionsAnswers(BaseModel):
    answer_start: int
    text: str


ListQuestionsAnswersByDisease.update_forward_refs()
ListQuestionsAnswersByDiseaseQas.update_forward_refs()
ListQuestionsAnswersByDiseaseQasArticle.update_forward_refs()
ListQuestionsAnswersByDiseaseQasQuestions.update_forward_refs()
ListQuestionsAnswersByDiseaseQasQuestionsAnswers.update_forward_refs()
