# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from typing import List

from pydantic import Field

from .base_model import BaseModel


class ListClassificationItems(BaseModel):
    classification_items: List["ListClassificationItemsClassificationItems"] = Field(
        alias="classificationItems"
    )


class ListClassificationItemsClassificationItems(BaseModel):
    id: str
    label: int
    article: "ListClassificationItemsClassificationItemsArticle"


class ListClassificationItemsClassificationItemsArticle(BaseModel):
    id: str
    text: str


ListClassificationItems.update_forward_refs()
ListClassificationItemsClassificationItems.update_forward_refs()
ListClassificationItemsClassificationItemsArticle.update_forward_refs()
