# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class SearchArticles(BaseModel):
    search_articles: Optional[List[str]] = Field(alias="searchArticles")


SearchArticles.update_forward_refs()
