# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from pydantic import Field

from .base_model import BaseModel


class Statistics(BaseModel):
    statistics: "StatisticsStatistics"


class StatisticsStatistics(BaseModel):
    disease_count: int = Field(alias="diseaseCount")
    articles_count: int = Field(alias="articlesCount")
    qas_count: int = Field(alias="qasCount")
    positive_classification_items_count: int = Field(
        alias="positiveClassificationItemsCount"
    )
    total_positive_classification_items_count: int = Field(
        alias="totalPositiveClassificationItemsCount"
    )
    negative_classification_items_count: int = Field(
        alias="negativeClassificationItemsCount"
    )
    qas_shortest_answer_length: int = Field(alias="qasShortestAnswerLength")
    qas_longest_answer_length: int = Field(alias="qasLongestAnswerLength")


Statistics.update_forward_refs()
StatisticsStatistics.update_forward_refs()
