# Generated by ariadne-codegen on 2023-08-19 23:26
# Source: thesis_diseases_risk_factors/graph/queries.graphqls

from pydantic import Field

from .base_model import BaseModel


class UpdateRiskFactors(BaseModel):
    update_risk_factors: "UpdateRiskFactorsUpdateRiskFactors" = Field(
        alias="updateRiskFactors"
    )


class UpdateRiskFactorsUpdateRiskFactors(BaseModel):
    stub: str = Field(alias="_stub")


UpdateRiskFactors.update_forward_refs()
UpdateRiskFactorsUpdateRiskFactors.update_forward_refs()
